### ISSUE TITLE
phateR - installation issue(s)

### ISSUE THREAD

**Issue by salvatoreloguercio** [KrishnaswamyLab/phateR#22]
Hello there,

I am trying to install phateR from source, but R CMD INSTALL returns:
ERROR: no packages specified

I tried R CMD INSTALL phateR but to no avail.

If attempting to install from devtool, I get:
devtools::install_github("KrishnaswamyLab/phateR")
[...]
Error in py_module_import(module, convert = convert) : 
ImportError: No module named phate

phateR loads without errors (library(phateR), but then when trying to use it, e.g. 
tree.phate <- phate(tree.data$data)
I get the same error:
Error in py_module_import(module, convert = convert) : 
ImportError: No module named phate

Further, it tries to install PHATE python package with reticulate, but gets stuck with the same error. 

Running R 3.4.3 and Python 3.6.3 (in Anaconda3) on a Mac OS 10.13.6 (High Sierra).
Thanks,
Sal

**Comment by scottgigante** [comment]
Hi @salvatoreloguercio ,

Sorry about the difficulty. Is there a specific reason you are installing from source rather than from CRAN?

If you could please run the following commands, I'll have you up and running in no time.

First, in a terminal:
```
which python
which pip
pip install --user phate
```
Then in python:
```
import phate
```
And finally, in R:
```
reticulate::conda_remove("r-reticulate")
reticulate::py_discover_config(required_module = "phate")
```
If you could please paste the results, we should be able to resolve this issue quickly.

**Comment by salvatoreloguercio** [comment]
Hi Scott,

Thanks for the quick answer! I get:
which python
/Users/sal/anaconda3/bin/python
which pip
/Users/sal/anaconda3/bin/pip

reticulate::py_discover_config(required_module = "phate")
python:         /Users/sal/anaconda3/bin/python
libpython:      /Users/sal/anaconda3/lib/libpython3.6m.dylib
pythonhome:     /Users/sal/anaconda3:/Users/sal/anaconda3
version:        3.6.3 |Anaconda custom (64-bit)| (default, Oct  6 2017, 12:04:38)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /Users/sal/.local/lib/python3.6/site-packages/numpy
numpy_version:  1.15.1
phate:          /Users/sal/.local/lib/python3.6/site-packages/phate

python versions found: 
 /usr/bin/python
 /usr/local/bin/python
 /Users/sal/anaconda3/bin/python
 /Users/sal/anaconda3/envs/orange3/bin/python

**Comment by salvatoreloguercio** [comment]
Thanks! Tried install_github with ref="dev", but got the same error message:

Reloading installed phateR
Error in py_module_import(module, convert = convert) : 
  ImportError: No module named phate

Then it goes again into the re-install loop:

Attempting to install PHATE python package with reticulate
[...]
Installation complete.

library(phateR)
tree.phate <- phate(tree.data$data)
Error in py_module_import(module, convert = convert) : 
  ImportError: No module named phate
Attempting to install PHATE python package with reticulate
[...]

**Comment by scottgigante** [comment]
Hmm. Can I ask you to run the following in R so I can see the python config after phateR is loaded?
```
library(phateR)
tree.phate <- phate(tree.data$data)
reticulate::py_config()
```
and then restart R and run
```
reticulate::py_discover_config(required_module = "phate")
retculate::import("phate")
library(phateR)
tree.phate <- phate(tree.data$data)
```

**Comment by salvatoreloguercio** [comment]
Yay! That worked. Thanks very much for your help!

>reticulate::py_config()
python:         /usr/bin/python
libpython:      /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
pythonhome:     /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
version:        2.7.10 (default, Oct  6 2017, 22:29:07)  [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
numpy:          /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy
numpy_version:  1.8.0
phate:          [NOT FOUND]

[restart R]

> reticulate::py_discover_config(required_module = "phate")
python:         /Users/sal/anaconda3/envs/r-reticulate/bin/python
libpython:      /Users/sal/anaconda3/envs/r-reticulate/lib/libpython3.7m.dylib
pythonhome:     /Users/sal/anaconda3/envs/r-reticulate:/Users/sal/anaconda3/envs/r-reticulate
version:        3.7.0 | packaged by conda-forge | (default, Aug 27 2018, 17:24:52)  [Clang 6.1.0 (clang-602.0.53)]
numpy:          /Users/sal/anaconda3/envs/r-reticulate/lib/python3.7/site-packages/numpy
numpy_version:  1.15.1
phate:          /Users/sal/anaconda3/envs/r-reticulate/lib/python3.7/site-packages/phate

python versions found: 
 /Users/sal/anaconda3/envs/r-reticulate/bin/python
 /usr/bin/python
 /usr/local/bin/python
 /Users/sal/anaconda3/bin/python
 /Users/sal/anaconda3/envs/orange3/bin/python

reticulate::import("phate")
Module(phate)
> library(phateR)
> tree.phate <- phate(tree.data$data)
Calculating PHATE...
Calculating graph and diffusion operator...
Calculating KNN search...
Calculated KNN search in 0.85 seconds.
Calculating affinities...
Calculated affinities in 0.04 seconds.
Calculated graph and diffusion operator in 0.90 seconds.
Calculating landmark operator...
Calculating SVD...
Calculated SVD in 0.34 seconds.
Calculating KMeans...
Calculated KMeans in 12.47 seconds.
Calculated landmark operator in 14.17 seconds.
Calculating optimal t...
Calculated optimal t in 2.80 seconds.
Automatically selected t = 8
Calculating diffusion potential...
Calculated diffusion potential in 0.40 seconds.
Calculating metric MDS...
Calculated metric MDS in 38.01 seconds.
Calculated PHATE in 56.28 seconds.

**Comment by scottgigante** [comment]
Glad it's working! A little odd as theoretically phateR should do that for you, but if it ain't broke, don't fix it :) 

For those coming late to this party: if PHATE is definitely installed but phateR doesn't find it, try running
```
reticulate::py_discover_config(required_module="phate")
```
before you import `phateR`. This _should_ happen by default with the code currently on master, expected to be on CRAN in approximately a week.
