### ISSUE TITLE
alpha_decay is deprecated

### ISSUE THREAD

**Issue by igordot** [KrishnaswamyLab/phateR#24]
I am getting the following warning:
```
/path/python3.6/site-packages/phate/phate.py:181: FutureWarning: alpha_decay is deprecated. Use `a=None` to disable alpha decay in future.
  " to disable alpha decay in future.", FutureWarning)
```
It looks like the actual command being called still includes `alpha_decay`. See: https://github.com/KrishnaswamyLab/phateR/blob/master/R/phate.R#L249

It's just a warning, so everything seems to work fine, but it might be worth fixing if it's not too much work.

**Comment by scottgigante** [comment]
Thanks @igordot for pointing this out! I'll put in a fix to the next maintenance release.
