### ISSUE TITLE
phate python installation issue

### ISSUE THREAD

**Issue by Ian2696** [KrishnaswamyLab/phateR#29]
Hello, 

I'm having an issue installing the python phate module before installing the phateR module in R. The module seems to install correctly upon running the following in my command line (MacOS 10.14). 

`pip install --user phate`

However upon running the `import phate` command within python (v3.6.1) I get the following error message....

`ValueError: not enough values to unpack (expected 2, got 1)`

I can't seem to get past this by following advise given relating to other installation issues. Any advise would be appreciated. 

Thanks 
Ian

**Comment by scottgigante** [comment]
Hi @Ian2696 , do you mind posting the full error message? There should be a traceback that tells you what line of code the error came from.

**Comment by scottgigante** [comment]
Might be related to https://github.com/KrishnaswamyLab/scprep/issues/33

**Comment by Ian2696** [comment]
Hi @scottgigante thanks for your quick reply. Here is the complete error message...

```
/Users/ian/anaconda/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ian/.local/lib/python3.6/site-packages/phate/__init__.py", line 5, in <module>
    import phate.io
  File "/Users/ian/.local/lib/python3.6/site-packages/phate/io.py", line 6, in <module>
    import scprep
  File "/Users/ian/.local/lib/python3.6/site-packages/scprep/__init__.py", line 5, in <module>
    import scprep.io
  File "/Users/ian/.local/lib/python3.6/site-packages/scprep/io/__init__.py", line 6, in <module>
    from .fcs import load_fcs
  File "/Users/ian/.local/lib/python3.6/site-packages/scprep/io/fcs.py", line 225, in <module>
    @utils._with_pkg("fcsparser")
  File "<decorator-gen-1>", line 2, in _with_pkg
  File "/Users/ian/anaconda/lib/python3.6/site-packages/decorator.py", line 228, in decorate
    evaldict, __wrapped__=func)
  File "/Users/ian/anaconda/lib/python3.6/site-packages/decorator.py", line 208, in create
    name, rest = obj.strip().split('(', 1)
ValueError: not enough values to unpack (expected 2, got 1)

```

**Comment by scottgigante** [comment]
No problem. Do you mind running the following in python?
```
import decorator
print(decorator.__version__)
```
After that, you can temporarily solve your issue by running from the command line:
```
pip install scprep==0.10.0
```

**Comment by Ian2696** [comment]
Thanks @scottgigante that seemed to work after running the following in python 

```
>>> import decorator
>>> print(decorator.__version__)
4.0.11
```

and then the following in terminal 

`pip install phate==0.2.9`

**Comment by scottgigante** [comment]
Thanks very @Ian2696 . I think the root cause of this is a `decorator` version incompatibility, but I can take it from here. I'll ping here when you're good to update `phate` and `scprep` to the latest versions.

**Comment by scottgigante** [comment]
@Ian2696 should be all fixed now. `pip install --upgrade phate` will have you all set.

**Comment by Ian2696** [comment]
@scottgigante thanks very much that has sorted it!
