### ISSUE TITLE
Is it possible to get n PHATE components?

### ISSUE THREAD

**Issue by davisidarta** [KrishnaswamyLab/phateR#35]
Hi!

I'm relatively new to PHATE (I've read your preprint, but I don't have that much of a math background). I'm wondering if it is possible to get n PHATE components for a given dataset. If so, is it possible to do it within phateR?

**Comment by scottgigante** [comment]
Hi @davisidarta, there is a parameter in the `phate` function called `ndim`. You can modify this to get a different number of components.
