### ISSUE TITLE
Changes to most recent rsvd::rpca function; unused argument (svdalg = "rsvd")

### ISSUE THREAD

**Issue by adourian1** [KrishnaswamyLab/phater#4]
Error in rsvd::rpca(X, ndim, retx = TRUE, svdalg = "rsvd") : 
  unused argument (svdalg = "rsvd")

**Comment by jennapappalardo** [comment]
I installed v6.0 of rsvd instead of v9.0 and it fixed that error for me
devtools::install_version("rsvd", version = "0.6")

**Comment by FlyingTeckel** [comment]
I'm just trying to run the example and keep getting this error:
> tree.phate <- phate(tree.data, 375, 15, 20, pca.method = 'none', mds.method = 'mmds')
[1] "No PCA performed"
[1] "MDS distance method: euclidean"
[1] "No PCA performed"
[1] "MDS method: mmds"
Error in rsvd::rpca(X, ndim, retx = TRUE, svdalg = "rsvd") : 
unused argument (svdalg = "rsvd")

I tried the earlier version of rsvd and it didn't help.

**Comment by krishpop** [comment]
should be fixed now, thanks for finding this issue!
