### ISSUE TITLE
How to accelerate phate() bu using parallel computation

### ISSUE THREAD

**Issue by pangxueyu233** [KrishnaswamyLab/phateR#42]

**Comment by scottgigante** [comment]
From [the documentation](https://www.rdocumentation.org/packages/phateR/versions/1.0.0/topics/phate):

**n.jobs**: _int, optional (default: 1) The number of jobs to use for the computation. If -1 all CPUs are used. If 1 is given, no parallel computing code is used at all, which is useful for debugging. For n.jobs below -1, (n.cpus + 1 + n.jobs) are used. Thus for n.jobs = -2, all CPUs but one are used_

**Comment by janxkoci** [comment]
Except when I use `n.jobs = -1` it still only runs on one core. Version `phateR_1.0.7`.
