### ISSUE TITLE
PHATE parameters

### ISSUE THREAD

**Issue by wuyinyu33** [KrishnaswamyLab/phateR#58]
Hi! I'm currently learning to use PHATE and might need help with the parameters. This is what I got after running the default settings of phate.
![phate](https://user-images.githubusercontent.com/87501088/125857426-b1bc5eb1-e105-49a1-9067-2773d1767ed7.png)

I wonder how I can change the parameters to make the branches separate more. I was expecting stretched-out branches of a rooted tree. 

(I tried gamma=0 and t=100, and I got this...)
![phate_gamma0](https://user-images.githubusercontent.com/87501088/125857576-13ce2ad3-8020-4199-818e-4752ddb45c53.png)

Thanks!

**Comment by LiuCanidk** [comment]
Hi @wuyinyu33 
Have you found out the rules of how to finely tune the parameter to get the 2D distribution more reasonable?
