### ISSUE TITLE
error with matplotlib  dependency for phate

### ISSUE THREAD

**Issue by abhay0305** [KrishnaswamyLab/phateR#61]
I was able to install numpy and all other python dependencies except matplotlib. Please let me know what is going on.  

> reticulate::py_install("matplotlib")
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

> reticulate::py_config()
python:         /opt/anaconda3/bin/python
libpython:      /opt/anaconda3/lib/libpython3.7m.dylib
pythonhome:     /opt/anaconda3:/opt/anaconda3
version:        3.7.6 (default, Jan  8 2020, 13:42:34)  [Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /opt/anaconda3/lib/python3.7/site-packages/numpy
numpy_version:  1.21.6
magic:          /opt/anaconda3/lib/python3.7/site-packages/magic

NOTE: Python version was forced by use_python function
> reticulate::py_discover_config()
python:         /opt/anaconda3/bin/python
libpython:      /opt/anaconda3/lib/libpython3.7m.dylib
pythonhome:     /opt/anaconda3:/opt/anaconda3
version:        3.7.6 (default, Jan  8 2020, 13:42:34)  [Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /opt/anaconda3/lib/python3.7/site-packages/numpy
numpy_version:  1.21.6

phate.tree <- phate(tree.data.small$data)
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'matplotlib.pyplot'
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'matplotlib.pyplot'

**System information:**

Output of `phate.__version__`:

```
Please run phate.__version__ and paste the results here.

You can do this with `python -c 'import phate; print(phate.__version__)'`
```

Output of `pd.show_versions()`:

<details>

```
Please run pd.show_versions() and paste the results here.

You can do this with `python -c 'import pandas as pd; pd.show_versions()'`
```

</details>

Output of `sessionInfo()`:

<details>

```
Please run sessionInfo() and paste the results here.

You can do this with `R -e 'library(phateR); sessionInfo()'`
```

</details>

Output of `reticulate::py_discover_config(required_module = "phate")`:

<details>

```
Please run `reticulate::py_discover_config(required_module = "phate")` and paste the results here.

You can do this with `R -e 'reticulate::py_discover_config(required_module = "phate")'`
```

</details>

Output of `phateR::check_pyphate_version()`:

<details>

```
Please run `phateR::check_pyphate_version()` and paste the results here.

You can do this with `R -e 'phateR::check_pyphate_version()'`
```

</details>

**Comment by scottgigante** [comment]
Can you please fill in the bug report information? I put the template in your comment. You can edit you comment by clicking on the three dots on the top right of your comment.

**Comment by abhay0305** [comment]
Hi,

Thanks for your response.

*Output of phate.__version__:*

*import phate *

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/Users/abhaykanodia/PHATE/Python/phate/__init__.py", line 3, in
<module>

    from .phate import PHATE

  File "/Users/abhaykanodia/PHATE/Python/phate/phate.py", line 17, in
<module>

    import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib.pyplot'


* print(phate.__version__)*


Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

NameError: name 'phate' is not defined




*Output of pd.show_versions():*

>>> import pandas as pd

>>> pd.show_versions()

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File
"/opt/anaconda3/lib/python3.7/site-packages/pandas/util/_print_versions.py",
line 109, in show_versions

    deps = _get_dependency_info()

  File
"/opt/anaconda3/lib/python3.7/site-packages/pandas/util/_print_versions.py",
line 88, in _get_dependency_info

    mod = import_optional_dependency(modname, errors="ignore")

  File
"/opt/anaconda3/lib/python3.7/site-packages/pandas/compat/_optional.py",
line 131, in import_optional_dependency

    version = get_version(module_to_get)

  File
"/opt/anaconda3/lib/python3.7/site-packages/pandas/compat/_optional.py",
line 60, in get_version

    raise ImportError(f"Can't determine version for {module.__name__}")

ImportError: Can't determine version for matplotlib




*Output of sessionInfo():*


R version 4.1.2 (2021-11-01)

Platform: x86_64-apple-darwin17.0 (64-bit)

Running under: macOS Big Sur 10.16


Matrix products: default

BLAS:
/Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.0.dylib

LAPACK:
/Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib


locale:

[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8


attached base packages:

[1] stats     graphics  grDevices utils     datasets  methods   base


other attached packages:

[1] phateR_1.0.7 Matrix_1.4-1


loaded via a namespace (and not attached):

 [1] Rcpp_1.0.8.3     magrittr_2.0.3   tidyselect_1.1.2 munsell_0.5.0

 [5] colorspace_2.0-3 lattice_0.20-45  R6_2.5.1         rlang_1.0.2

 [9] fastmap_1.1.0    fansi_1.0.3      dplyr_1.0.9      grid_4.1.2

[13] gtable_0.3.0     png_0.1-7        utf8_1.2.2       cli_3.3.0

[17] DBI_1.1.2        ellipsis_0.3.2   assertthat_0.2.1 tibble_3.1.7

[21] lifecycle_1.0.1  crayon_1.5.1     purrr_0.3.4      ggplot2_3.3.6

[25] vctrs_0.4.1      cachem_1.0.6     memoise_2.0.1    glue_1.6.2

[29] compiler_4.1.2   pillar_1.7.0     generics_0.1.2   scales_1.2.0

[33] jsonlite_1.8.0   reticulate_1.24  pkgconfig_2.0.3

>




*Output of reticulate::py_discover_config(required_module = "phate"):  When
I run on R*


python:         /opt/anaconda3/bin/python
libpython:      /opt/anaconda3/lib/libpython3.7m.dylib
pythonhome:     /opt/anaconda3:/opt/anaconda3
version:        3.7.6 (default, Jan  8 2020, 13:42:34)  [Clang 4.0.1
(tags/RELEASE_401/final)]
numpy:          /opt/anaconda3/lib/python3.7/site-packages/numpy
numpy_version:  1.21.6
phate:
 /Users/abhaykanodia/.local/lib/python3.7/site-packages/phate-1.0.7-py3.7.egg/phate

NOTE: Python version was forced by use_python function



*Output of reticulate::py_discover_config(required_module = "phate"):  When
I run on Terminal*



*Error in python_config_impl(python) : *

*  Error 137 occurred running
/Users/abhaykanodia/.virtualenvs/r-reticulate/bin/python: *

*In addition: Warning message:*

*In system2(command = python, args = shQuote(script), stdout = TRUE,  :*

*  running command
''/Users/abhaykanodia/.virtualenvs/r-reticulate/bin/python'
'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/reticulate/config/config.py'
2>/dev/null' had status 137*




*Output of phateR::check_pyphate_version():*


> phateR::check_pyphate_version()
Error: $ operator is invalid for atomic vectors




Thanks a lot!


Best,

Abhay

**Comment by scottgigante** [comment]
Looks like you need to install matplotlib by running (from terminal)
```
python -m pip install matplotlib
```
and upgrade phateR by running (from R)
```
install.packages("phateR")
```

Can you please do that and then try again?

**Comment by abhay0305** [comment]
Hi,

I was able to resolve the issue but now the issue is with magic now. I
would be very grateful if I could resolve this issue.

Thank you!

Best,

Abhay

**Comment by scottgigante** [comment]
Hi @abhay0305, please open a [bug report in MAGIC](https://github.com/KrishnaswamyLab/MAGIC/issues/new?assignees=&labels=bug&template=bug_report.md&title=) to resolve this. Thanks!

**Comment by abhay0305** [comment]
Hi,

Thanks a lot again for your help. I ran what you said and this is the
output.

*(base) MacBook-Pro:Python abhaykanodia$ python -m pip install matplotlib*


Requirement already satisfied: matplotlib in
/opt/anaconda3/lib/python3.7/site-packages (3.1.3)

Requirement already satisfied: python-dateutil>=2.1 in
/opt/anaconda3/lib/python3.7/site-packages (from matplotlib) (2.8.2)

Requirement already satisfied: cycler>=0.10 in
/opt/anaconda3/lib/python3.7/site-packages (from matplotlib) (0.11.0)

Requirement already satisfied: kiwisolver>=1.0.1 in
/opt/anaconda3/lib/python3.7/site-packages (from matplotlib) (1.4.2)

Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in
/opt/anaconda3/lib/python3.7/site-packages (from matplotlib) (3.0.8)

Requirement already satisfied: numpy>=1.11 in
/opt/anaconda3/lib/python3.7/site-packages (from matplotlib) (1.21.6)

Requirement already satisfied: typing-extensions in
/opt/anaconda3/lib/python3.7/site-packages (from
kiwisolver>=1.0.1->matplotlib) (4.2.0)

Requirement already satisfied: six>=1.5 in
/opt/anaconda3/lib/python3.7/site-packages (from
python-dateutil>=2.1->matplotlib) (1.16.0)



(base) MacBook-Pro:Python abhaykanodia$ Python

Python 3.7.6 (default, Jan  8 2020, 13:42:34)

[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin

Type "help", "copyright", "credits" or "license" for more information.



>>> *import phate*

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/Users/abhaykanodia/PHATE/Python/phate/__init__.py", line 3, in
<module>

    from .phate import PHATE

  File "/Users/abhaykanodia/PHATE/Python/phate/phate.py", line 17, in
<module>

    import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib.pyplot'


Thanks!


Best,

Abhay

**Comment by scottgigante** [comment]
PHATE doesn't appear to be installed correctly. What happens if you run

```
/opt/anaconda3/lib/python3.7/python -m pip install --upgrade phate
/opt/anaconda3/lib/python3.7/python
>>> import phate
```
