### ISSUE TITLE
Determining highest contributing variables possible?

### ISSUE THREAD

**Issue by bananabenana** [KrishnaswamyLab/phateR#67]
Hi,

First off, wanted to say how much I am enjoying using PHATE, this is a great tool.

I am not sure if I have missed this in the documentation, but is there any way I can identify the highest contributing variables for a PHATE plot?
For example, using the `fviz_pca_var` function from `factoextra` you can identify the top x variables. Example code block:
```
pca_vars_top_20 <- fviz_pca_var(pca,
             col.var = "contrib", # Color by contributions to the PC
             repel = TRUE, # Avoid text overlapping
             max.overlaps = Inf,
             gradient.cols = c("#FEB24C", "#FC4E2A", "#800026"),
             legend.title = "Contribution", 
             select.var = list(contrib = 20), # change this to increase number of highest contributing variables
             ) + 
  xlab("PC1") +
  ylab("PC2")
```
This outputs a ranked plot. 

Does this or a similar functionality exist for PHATE? Not so much the plot per se, just being able to see the most important variables that cause the PHATE distributions.

Thanks

**Comment by kmoon3** [comment]
Hi,

See the answer to a similar question at https://github.com/KrishnaswamyLab/phateR/issues/70. The short answer is you can't do this directly, but there are some workarounds.

**Comment by bananabenana** [comment]
Ah cool thanks. I didn't see this issue
